import os

lines = []

def add(s=''):
    lines.append(s)

add('# Sign Language AI System -- Enhancement Plan')
add()
add('## 1. Current System Analysis')
add()
add('### What Exists Today')
add()
add('The project currently has **two separate, isolated pipelines** controlled by a CLI menu:')
add()
add('| Component | Static Signs (A-Z) | Motion Signs (Hello, Thank You...) |')
add('|---|---|---|')
add('| **Algorithm** | Random Forest (scikit-learn) | Dynamic Time Warping (DTW) |')
add('| **Input** | Single frame (63 features) | Sequence of frames (60 x 63 matrix) |')
add('| **Trigger** | User selects Option 3, 3-second timer, stops | User selects Option 5, 5-second timer, stops |')
add('| **Data** | hand_landmarks.csv | motion_signs/name/*.npy |')
add('| **Detection** | MediaPipe Hands (1 hand) | MediaPipe Hands (1-2 hands) |')
add('| **Output** | gTTS output.mp3 | gTTS motion_output.mp3 |')
add()
add('### Identified Limitations')
add()
add('1. **Manual mode switching** -- User must choose static or motion from a menu before each detection session. There is no unified mode.')
add('2. **Timer-based capture** -- Static mode runs for exactly 3 seconds, motion mode for 5 seconds. There is no continuous detection.')
add('3. **No real-time auto-detection** -- The system does not automatically recognize when a sign starts or ends in a continuous video stream.')
add('4. **No confidence-based triggering** -- Results are only shown after the timer expires, not when a confident prediction is made.')
add('5. **No cooldown/deduplication** -- If the system were continuous, it would repeatedly detect the same sign.')
add('6. **Single-hand constraint for static** -- Static pipeline only uses 1 hand (63 features). Two-handed signs cannot be detected.')
add('7. **No web interface** -- Only works through local CLI + OpenCV window. Cannot be demoed remotely or in a browser.')
add('8. **No deep learning model** -- The planned BiLSTM + Attention architecture from FINAL_YEAR_PROJECT_PLAN.md has not been implemented yet.')
add('9. **No idle/background class** -- The system has no way to distinguish not signing from signing, leading to false positives.')
add('10. **No data augmentation** -- Training data is raw, with no rotation, noise, or speed variations to improve generalization.')
add()
add('---')
add()
add('## 2. Proposed Enhancements')
add()
add('### Enhancement A: Unified Continuous Real-Time Detection Engine')
add()
add('**Goal:** Replace the two separate pipelines with a single continuous detection loop that recognizes both static and motion signs simultaneously, without any menu interaction.')
add()
add('**How it works:**')
add('- A sliding window buffer maintains the last 60 frames (~2 seconds at 30 FPS).')
add('- Every ~300ms (every 9th frame), the system runs inference:')
add('  - **For static signs:** The latest single frame is checked against the classifier.')
add('  - **For motion signs:** The full 60-frame window is checked against the sequence model.')
add('- The system picks the best prediction across both pipelines.')
add('- When confidence exceeds a threshold (default 80%) for 3 consecutive evaluations, the sign is auto-triggered and spoken via TTS.')
add('- A 2-second cooldown prevents the same sign from being spoken repeatedly.')
add('- An Idle/No Sign class prevents false positives when the user is not signing.')
add()
add('**Key components:**')
add()
add('    Camera Feed -> MediaPipe -> Frame Buffer (deque, maxlen=60)')
add('                                      |')
add('                        +-------------+------------+')
add('                        v                          v')
add('                Single-Frame Path           Sequence Path')
add('                (Random Forest)             (DTW / Deep Learning)')
add('                        |                          |')
add('                        +-------------+------------+')
add('                                      v')
add('                        Confidence Comparator')
add('                                      |')
add('                                      v')
add('                        Auto-Trigger + Cooldown + TTS')
print('Part 1 written')

add()
add('### Enhancement B: Deep Learning Model (BiLSTM + Attention)')
add()
add('**Goal:** Replace the Random Forest + DTW combo with a single unified neural network that handles both static and motion signs in one forward pass.')
add()
add('**Architecture:**')
add()
add('| Layer | Details |')
add('|---|---|')
add('| **Input** | (batch, 60 frames, 138 features) -- dual hand + pose from MediaPipe Holistic |')
add('| **Feature Projection** | Linear(138 to 128) -> BatchNorm1d -> ReLU -> Dropout(0.3) |')
add('| **BiLSTM** | 2 layers, hidden=128, bidirectional, dropout=0.3 |')
add('| **Self-Attention** | Learned attention weights over 60 time steps -> weighted sum -> context vector |')
add('| **Classifier** | Linear(256 to 64) -> ReLU -> Dropout(0.3) -> Linear(64 to num_classes) |')
add('| **Output** | Softmax over all sign classes + Idle class |')
add()
add('**Why this works for both static and motion signs:**')
add('- A static sign (e.g., letter A) appears as 60 nearly identical frames -> the model learns the fixed spatial shape.')
add('- A motion sign (e.g., Hello) appears as 60 frames with a movement trajectory -> the model learns the temporal pattern.')
add('- The attention mechanism automatically weights the most informative frames.')
add()
add('**Training pipeline:**')
add('- Dataset: 30+ sequences per sign class, each 60 frames of 138 features.')
add('- Augmentation: Gaussian noise (sigma=0.01), random rotation (+/-15 degrees), random scale (0.85x-1.15x), temporal speed warping, hand dropout.')
add('- Optimizer: AdamW with learning rate scheduling.')
add('- Loss: CrossEntropyLoss with class weights (to handle imbalance with the Idle class).')
add('- Evaluation: Confusion matrix, precision/recall/F1 per class, loss/accuracy curves.')
add('- Export: PyTorch .pt file, optional ONNX export for faster inference.')
add()
add('**Fallback:** If no deep learning model is trained yet, the system falls back to Random Forest + DTW using the existing algorithms.')
add()
add('### Enhancement C: Gradio Web Interface')
add()
add('**Goal:** Provide a browser-based GUI that works locally or can be deployed to Google Colab, replacing the CLI-only workflow.')
add()
add('**Interface layout:**')
add()
add('| Tab | Features |')
add('|---|---|')
add('| **Live Detection** | Webcam feed with overlaid predictions, confidence bars, detection history log, auto-spoken audio |')
add('| **Record New Sign** | Text input for sign name, record button, visual countdown, frame counter, save to dataset |')
add('| **Train Model** | Button to start training, progress bar, epoch counter, accuracy display, confusion matrix image |')
add('| **Dataset Manager** | Table showing all recorded signs with frame counts, bar chart of class distribution, delete buttons |')
add('| **Settings** | Sliders for confidence threshold (50-99%), cooldown duration (0.5-5s), detection mode toggle, webcam device selector |')
add()
add('**Technical implementation:**')
add('- Framework: Gradio (lightweight, Colab-compatible, no frontend code needed)')
add('- Webcam: Gradio Webcam component for input')
add('- Audio: Gradio Audio component for TTS playback')
add('- Detection runs in a background thread, updating a shared state object')
add('- Results displayed in real-time via Gradio reactive updates')
add()
add('---')
add()
add('## 3. MediaPipe Holistic Upgrade (Dual Hand + Pose)')
add()
add('**Current:** MediaPipe Hands -> 1 hand -> 21 landmarks -> 63 features per frame.')
add()
add('**Upgrade:** MediaPipe Holistic -> 2 hands + upper body pose -> 138 features per frame.')
add()
add('| Body Part | Landmarks | Features |')
add('|---|---|---|')
add('| Left Hand | 21 keypoints x 3D | 63 |')
add('| Right Hand | 21 keypoints x 3D | 63 |')
add('| Upper Body Pose (shoulders + elbows) | 4 keypoints x 3D | 12 |')
add('| **Total** | | **138** |')
add()
add('This enables detection of two-handed signs (e.g., letters T, U, etc. in ASL) and provides body context for more accurate classification.')
add()
add('**Fallback:** If Holistic fails to detect both hands, the system pads missing hand features with zeros and continues with available data.')
add()
add('---')
print('Part 2 written')
